-- Replicas --

// alias -> address
// ap-south-1     127.0.0.1
// ap-northeast-1 127.0.0.2
// eu-west-3      127.0.0.3

-- Clients --

// alias -> address
ap-east-1      127.0.1.1

-- Master --

// alias -> address
us-west-1 127.0.2.1

masterPort: 7087

protocol: Paxos

// Replicas
noop:       false // do not execute
thrifty:    false
optread:    false
leaderless: false
fast:       true

// Clients
reqs:        1
runTime:     none // 5min
writes:      100
conflicts:   2
commandSize: 1000
clones:      0
key:         42 // conflicting key

pipeline: false
pendings: 10000

-- Proxy --
server_alias ap-south-1
server_alias ap-northeast-1
server_alias eu-west-3
---
